### ISSUE TITLE
We'll need to make small adjustments to `CITATION.cff`

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification-pdf-releases#2]
This is the current `CITATION.cff` in the bids spec repo:

https://github.com/bids-standard/bids-specification/blob/master/CITATION.cff

I think when copying the file over here at release time, there are some adjustments we need to make, in particular for these lines:

https://github.com/bids-standard/bids-specification/blob/51a40fba7fa5b2a41c62802dd2329fe617f8ae04/CITATION.cff#L15

https://github.com/bids-standard/bids-specification/blob/51a40fba7fa5b2a41c62802dd2329fe617f8ae04/CITATION.cff#L19C1-L22C10

cc @Remi-Gau 

... Having said this, perhaps we should not "Zenodo-archive" the bids spec repo, as it will create confusion? 🤔

**Comment by Remi-Gau** [comment]
> we should not "Zenodo-archive" the bids spec repo, as it will create confusion?

agreed: let's not

**Comment by Remi-Gau** [comment]
> https://github.com/bids-standard/bids-specification/blob/51a40fba7fa5b2a41c62802dd2329fe617f8ae04/CITATION.cff#L19C1-L22C10

We can have several identifiers in citation.cff I think. So I would not necesarily worry about this on.

**Comment by sappelhoff** [comment]
> agreed: let's not

ok, disabled it ✅ 

> We can have several identifiers in citation.cff I think. So I would not necesarily worry about this on.

ok great :-)

**Comment by sappelhoff** [comment]
adjustments will be made here:

- https://github.com/bids-standard/bids-specification/pull/1659

and then transferred to this repo upon the next release
